name: deploy

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v8.0.0
        name: Setup uv

      - name: Build
        run: |
          uv run python -m build
          uv run twine check dist/*
